Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Controllers/ClienteController.cs
using LojaNet.DAL;
using LojaNet.Models;
using LojaNET.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaNET.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        private ICliente bll;

        public ClienteController()
        {
            bll = AppContainer.ObterClienteBLL();
        }

        // GET: Cliente
        public ActionResult Index()
        {
            var list = bll.ObterTodos();

            return View(list);
        }

        public ActionResult Incluir()
        {
            var cliente = new Cliente();

            return View(cliente);
        }

        [HttpPost]
        public ActionResult Incluir(Cliente cliente)
        {
            try
            {
                bll.Incluir(cliente);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return View(cliente);
            }
        }

        public ActionResult Alterar(string id)
        {
            var cliente = bll.ObterPorId(id);

            return View(cliente);
        }

        [HttpPost]
        public ActionResult Alterar(Cliente cliente)
        {
            try
            {
                bll.Alterar(cliente);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return View(cliente);
            }
        }

        public ActionResult Excluir(string id)
        {
            var cliente = bll.ObterPorId(id);

            return View(cliente);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            try
            {
                bll.Excluir(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                var cliente = bll.ObterPorId(id);
                return View(cliente);
            }
        }

        public ActionResult Detalhes(string id)
        {
            var cliente = bll.ObterPorId(id);

            return View(cliente);
        }
    }
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaNET.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Controllers/ProdutoController.cs
using LojaNet.Models;
using LojaNET.Models.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaNET.UI.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private IProduto bll;

        public ProdutoController()
        {
            bll = AppContainer.ObterProdutoBLL();
        }

        // GET: Produto
        public ActionResult Index()
        {
            var list = bll.ObterTodos();

            return View(list);
        }

        public ActionResult Incluir()
        {
            var produto = new Produto();

            return View(produto);
        }

        [HttpPost]
        public ActionResult Incluir(Produto produto)
        {
            try
            {
                bll.Incluir(produto);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return View(produto);
            }
        }

        public ActionResult Alterar(string id)
        {
            var produto = bll.ObterPorId(id);

            return View(produto);
        }

        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            try
            {
                bll.Alterar(produto);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return View(produto);
            }
        }

        public ActionResult Excluir(string id)
        {
            var produto = bll.ObterPorId(id);

            return View(produto);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            try
            {
                bll.Excluir(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                var produto = bll.ObterPorId(id);
                return View(produto);
            }
        }

        public ActionResult Detalhes(string id)
        {
            var produto = bll.ObterPorId(id);

            return View(produto);
        }
    }
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Cliente/Alterar.cshtml
@model LojaNet.Models.Cliente

@{
    ViewBag.Title = "Alterar Cliente";
}

<h2>Alterar Cliente</h2>

<hr />

@using (Html.BeginForm("Alterar", "Cliente", FormMethod.Post, new { @id = "FormCliente", @class = "form-vertical" }))
{

    @Html.ValidationSummary(null, new { @class = "text-danger" })

    @Html.HiddenFor(x => Model.id)

    <div class="form-group">
        <label class="control-label" for="nome">Nome: </label>
        @Html.TextBoxFor(x => Model.nome, new { @class = "form-control", @placeholder = "Digite o nome" })
    </div>
    <div class="form-group">
        <label class="control-label" for="telefone">Telefone: </label>
        @Html.TextBoxFor(x => Model.telefone, new { @type = "tel", @class = "form-control", @placeholder = "Digite o telefone" })
    </div>
    <div class="form-group">
        <label class="control-label" for="email">Email: </label>
        @Html.TextBoxFor(x => Model.email, new { @type = "email", @class = "form-control", @placeholder = "Digite o email" })
    </div>

    <button class="btn btn-success" type="submit">Salvar</button>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Cliente/Detalhes.cshtml
@model LojaNet.Models.Cliente

@{
    ViewBag.Title = "Detalhes";
}

<h2>Dados do Cliente</h2>

<hr />

<div class="form-vertical">
    <dl>
        <dt>
            Código: 
        </dt>
        <dd>
            @Model.id
        </dd>

        <dt>
            Nome:
        </dt>
        <dd>
            @Model.nome
        </dd>

        <dt>
            Email:
        </dt>
        <dd>
            @Model.email
        </dd>

        <dt>
            Telefone: 
        </dt>
        <dd>
            @Model.telefone
        </dd>
    </dl>

    <hr />

    <div class="btn-group">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Alterar", "Alterar", new { id = Model.id }, new { @class = "btn btn-warning" })
        @Html.ActionLink("Excluir", "Excluir", new { id = Model.id }, new { @class = "btn btn-danger" })
    </div>
</div>

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Cliente/Excluir.cshtml
@model LojaNet.Models.Cliente

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<hr />

<h4>Confirmar a exclusão desse cliente ?</h4>

<p>
    @Model.nome
</p>

<hr />

@using (Html.BeginForm("Excluir", "Cliente", FormMethod.Post, new { id = Model.id, form = Model }))
{
    <div class="btn-group">
        @Html.ActionLink("Voltar", "Detalhes", new { id = Model.id }, new { @class = "btn btn-default" })
        <input type="submit" value="Excluir" class = "btn btn-danger" />
    </div>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Cliente/Incluir.cshtml
@model LojaNet.Models.Cliente

@{
    ViewBag.Title = "Novo Cliente";
}

<h2>Novo Cliente</h2>

<hr />

@using (Html.BeginForm("Incluir", "Cliente", FormMethod.Post, new { @id="FormCliente", @class="form-vertical" })) {
    
    @Html.ValidationSummary(null, new { @class="text-danger" })
    
    <div class="form-group">
        <label class="control-label" for="nome">Nome: </label>
        @Html.TextBoxFor(x => Model.nome, new { @class = "form-control", @placeholder = "Digite o nome" })
    </div>
    <div class="form-group">
        <label class="control-label" for="telefone">Telefone: </label>
        @Html.TextBoxFor(x => Model.telefone, new { @type = "tel", @class = "form-control", @placeholder = "Digite o telefone" })
    </div>
    <div class="form-group">
        <label class="control-label" for="email">Email: </label>
        @Html.TextBoxFor(x => Model.email, new { @type = "email", @class = "form-control", @placeholder = "Digite o email" })
    </div>
    
    <button class="btn btn-success" type="submit">Cadastrar</button>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Cliente/Index.cshtml
@model IEnumerable<LojaNet.Models.Cliente>

@{
    ViewBag.Title = "Clientes";
}

<h2>Clientes</h2>

<hr />

<div class="form-group">
    @Html.ActionLink("Novo", "Incluir", "Cliente", new { @class = "btn btn-primary" })
</div>

<div class="form-group">
    <table class="table table-bordered table-hover table-striped table-responsive">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cliente in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(cliente.nome, "Detalhes", "Cliente", new { id = cliente.id }, htmlAttributes: null)
                    </td>
                    <td>@cliente.email</td>
                    <td>@cliente.telefone</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Produto/Alterar.cshtml
@model LojaNet.Models.Produto

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar Produto</h2>

<hr />

@using (Html.BeginForm("Alterar", "Produto", FormMethod.Post, new { @id = "FormProduto", @class = "form-vertical" }))
{

    @Html.ValidationSummary(null, new { @class = "text-danger" })

    @Html.HiddenFor(x => Model.id)

    <div class="form-group">
        <label class="control-label" for="nome">Nome: </label>
        @Html.TextBoxFor(x => Model.nome, new { @class = "form-control", @placeholder = "Digite o nome" })
    </div>
    <div class="form-group">
        <label class="control-label" for="telefone">Preço: </label>
        @Html.TextBoxFor(x => Model.preco, new { @type = "text", @class = "form-control", @placeholder = "Digite o preço" })
    </div>
    <div class="form-group">
        <label class="control-label" for="email">Qtd Estoque: </label>
        @Html.TextBoxFor(x => Model.estoque, new { @type = "number", @class = "form-control", @placeholder = "Digite a quantidade no estoque" })
    </div>

    <button class="btn btn-success" type="submit">Salvar</button>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Produto/Detalhes.cshtml
@model LojaNet.Models.Produto

@{
    ViewBag.Title = "Detalhes";
}

<h2>Dados do Produto</h2>

<hr />

<div class="form-vertical">
    <dl>
        <dt>
            Código:
        </dt>
        <dd>
            @Model.id
        </dd>

        <dt>
            Nome:
        </dt>
        <dd>
            @Model.nome
        </dd>

        <dt>
            Preço:
        </dt>
        <dd>
            @Model.preco.ToString("c")
        </dd>

        <dt>
            Qtd Estoque:
        </dt>
        <dd>
            @Model.estoque
        </dd>
    </dl>

    <hr />

    <div class="btn-group">
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Alterar", "Alterar", new { id = Model.id }, new { @class = "btn btn-warning" })
        @Html.ActionLink("Excluir", "Excluir", new { id = Model.id }, new { @class = "btn btn-danger" })
    </div>
</div>

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Produto/Excluir.cshtml
@model LojaNet.Models.Produto

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<hr />

<h4>Confirmar a exclusão desse produto ?</h4>

<p>
    @Model.nome
</p>

<hr />

@using (Html.BeginForm("Excluir", "Produto", FormMethod.Post, new { id = Model.id, form = Model }))
{
    <div class="btn-group">
        @Html.ActionLink("Voltar", "Detalhes", new { id = Model.id }, new { @class = "btn btn-default" })
        <input type="submit" value="Excluir" class="btn btn-danger" />
    </div>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Produto/Incluir.cshtml
@model LojaNet.Models.Produto

@{
    ViewBag.Title = "Incluir";
}

<h2>Novo Produto</h2>

<hr />

@using (Html.BeginForm("Incluir", "Produto", FormMethod.Post, new { @id = "FormProduto", @class = "form-vertical" }))
{

    @Html.ValidationSummary(null, new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label" for="nome">Nome: </label>
        @Html.TextBoxFor(x => Model.nome, new { @class = "form-control", @placeholder = "Digite o nome" })
    </div>
    <div class="form-group">
        <label class="control-label" for="telefone">Preço: </label>
        @Html.TextBoxFor(x => Model.preco, new { @type = "text", @class = "form-control", @placeholder = "Digite o preço" })
    </div>
    <div class="form-group">
        <label class="control-label" for="email">Qtd Estoque: </label>
        @Html.TextBoxFor(x => Model.estoque, new { @type = "number", @class = "form-control", @placeholder = "Digite a quantidade no estoque" })
    </div>

    <button class="btn btn-success" type="submit">Cadastrar</button>
}

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Produto/Index.cshtml
@model IEnumerable<LojaNet.Models.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Produtos</h2>

<hr />

<div class="form-group">
    @Html.ActionLink("Novo", "Incluir", "Produto", new { @class = "btn btn-primary" })
</div>

<div class="form-group">
    <table class="table table-bordered table-hover table-striped table-responsive">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var produto in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(produto.nome, "Detalhes", "Produto", new { id = produto.id }, htmlAttributes: null)
                    </td>
                    <td>@produto.preco.ToString("c")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Curso_C#_Modulo_II_(Intermediario)/LojaNET/LojaNET.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Loja NET", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                    <li>@Html.ActionLink("Pedidos", "Index", "Pedido")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Loja NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>