E_SalesLojaVirtual/E_SalesLojaVirtual/Controllers/AutenticacaoClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using E_SalesLojaVirtual.Models.AutenticacaoCliente;
using E_SalesLojaVirtual.Models.CarrinhoDeCompras;
using E_SalesLojaVirtual.Models;

namespace E_SalesLojaVirtual.Controllers
{
    public class AutenticacaoClienteController : Controller
    {
        // GET: CadastrarCliente
        public ActionResult CadastrarCliente()
        {
            return View();
        }

        // POST: CadastrarCliente
        [HttpPost]
        public ActionResult CadastrarCliente(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                CRUD_Cliente crud = new CRUD_Cliente();

                crud.CadastrarCliente(cliente);

                return RedirectToAction("Index", "Home");
            }

            return View("CadastrarCliente", cliente);
        }

        // GET: LoginCliente
        public ActionResult LoginCliente()
        {
            return View();
        }

        // POST: LoginCliente
        [HttpPost]
        public ActionResult LoginCliente(Cliente cliente)
        {
            CRUD_Cliente crud = new CRUD_Cliente();

            Cliente c = crud.RetornaCliente(cliente.email, cliente.senha);

            if (c != null)
            {
                Carrinho carrinho = new Carrinho();

                carrinho.cliente = c;

                Session["Carrinho"] = carrinho;

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Cliente = 1;

                return View("LoginCliente", cliente);
            }
        }

        // GET: VerificaSessaoCliente
        public ActionResult VerificaSessaoCliente()
        {
            if (Session["Carrinho"] != null)
            {
                Carrinho carrinho = (Carrinho)Session["Carrinho"];

                ViewBag.NomeCliente = carrinho.cliente.nome;

                return PartialView("ClienteLoginNavBar");
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: RedefinirSenha
        public ActionResult RedefinirSenha()
        {
            return View();
        }

        // POST: RedefinirSenha
        [HttpPost]
        public ActionResult RedefinirSenha(Cliente cliente)
        {
            CRUD_Cliente crud = new CRUD_Cliente();

            crud.EditarCliente(cliente);

            return RedirectToAction("Index", "Home");
        }

        // GET: LogoutCliente
        public ActionResult LogoutCliente()
        {
            Session.Remove("Carrinho");

            return RedirectToAction("Index", "Home");
        }
    }
}

E_SalesLojaVirtual/E_SalesLojaVirtual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Validator.css")
    @Styles.Render("~/Content/Utils.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: #A8A8A8;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Home/Index">
                    <img src="~/img/logo.jpg" width="75" height="50" style="float:left" />
                </a>
                @*@Html.ActionLink("E-Sales", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Departamentos", "Index", "Departamentos")</li>
                    @*<li>@Html.ActionLink("Devoluções", "Devolucoes", "Home")</li>*@
                </ul>

                @if (Session["Carrinho"] == null)
                {
                    <ul class="nav navbar-nav" style="float:right">
                        <li>@Html.ActionLink("Cadastre-se", "CadastrarCliente", "AutenticacaoCliente")</li>
                        <li>@Html.ActionLink("Login", "LoginCliente", "AutenticacaoCliente")</li>
                    </ul>
                }
                else
                {
                    Html.RenderAction("VerificaSessaoCliente", "AutenticacaoCliente");
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Sales</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/all")
    @*@RenderSection("scripts", required: false)*@

</body>
</html>